name: build

on:
  push:

jobs:
  build_arm32v7:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: setup QEMU
        uses: docker/setup-qemu-action@v1.2.0
        with:
          platforms: arm

      - name: setup docker buildx
        uses: docker/setup-buildx-action@v1.6.0

      - name: build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.arm32v7
